New questiontype 143 rebased
makrei-p/unipark pull request #14
Opened 2022-04-05 13:29 UTC by JulianFrattini

Implemented handling of the 143 question type (now labeled "freematrix") as well as a refactoring of the plots in the report auto gen notebook. This introduced the following major changes:

- The "paths.json" file is replaced by a general "configuration.json" file, where for each question type an array of configurations can be given (in addition to the old paths-values). For each of these generations, the report auto gen notebook creates an individual plot, enabling customizable visualizations per question type.
- All visualizations have been moved into the src/unipark/utils/plots folder. Here, one file takes care of each question type.

The following aspects are still missing:

- The visualization of worldmaps has not been tested. The code has just been moved.
- The old plots.py file can be removed once deemed superfluous.

2022-04-07 19:22 UTC, makrei-p requested changes
Looks good in general, only a few remarks. 

However, there are quite a few whitespace warnings by pylint (`pylint $(find . -type f -name "*.py" ! -path "**/.venv/**")`), you can fix most of them by using the reformat file feature in PyCharm !

2022-04-07 19:22 UTC, makrei-p commented on src/unipark/utils/plots/single.py
> +    while exists(f'{file_prefix}_{index}.png'):
Is this so that when re-running the script you'll get a different index?

2022-04-07 19:22 UTC, makrei-p commented on unipark/codebook/code_book_parser.py
> +import pandas as pd
This file (and the whole `/unipark` folder) should not exist? At least it is doubling `/src/unipark/...`

2022-04-07 19:22 UTC, makrei-p commented on src/unipark/utils/plots/single.py
> +    ax.bar_label(barc, label_type='edge')
please check your matplotlib version and eventually update requirements.txt accordingly! On my side I'm getting an `AttributeError: 'AxesSubplot' object has no attribute 'bar_label'`!

2022-04-08 07:33 UTC, JulianFrattini commented on notebooks/configuration.json
> +    "input_csv": "../../../../../../Documents/Promotion/Projects/[RED] Requirements Engineering Debt/Data/2021 Understanding Requirements Debt/4_Survey/data_project_786665_2022_02_03.csv",
True. I will change that.

2022-04-08 07:36 UTC, JulianFrattini commented on src/unipark/utils/plots/single.py
> +    while exists(f'{file_prefix}_{index}.png'):
Exactly. For the use case where a user defines multiple configurations per question type (e.g., for questions of type "single" a user always wants to see two bar charts, one with all respondents, one with only finishers) the names of the charts may overlap. Alternatively, we could make the figure names more explicit (e.g., qXXXXXX-bar-finishers-ordered.png). I am not a big fan of these long filenames, but in case you prefer that I also have no issue with changing the code.

2022-04-08 07:37 UTC, JulianFrattini commented on unipark/codebook/code_book_parser.py
> +import pandas as pd
Indeed. A general cleanup of the files in the repo would be necessary, but I would rather have you do that, since you have a better overview of the files. I have not touched anything in the unipark/ folder and I guess that all the code in there is obsolete.

2022-04-08 07:38 UTC, JulianFrattini commented on src/unipark/utils/plots/single.py
> +    ax.bar_label(barc, label_type='edge')
Thanks for the info, you are absolutely right. The bar_label attribute is available from version 3.4.2 on, which I have now specified in the requirements.

2022-05-08 13:36 UTC, makrei-p approved these changes
LGTM! Thanks for the contribution (and sorry for the late review)!

2022-05-08 13:38 UTC, merged